### ISSUE TITLE
Multiline edit

### ISSUE THREAD

**Issue by S0und** [astropanic/Compline#1]
Hi

I love your work, my question is, can we see a multi-line version of this plugin?

**Comment by MrRaffnix** [comment]
I can not guess the user interface for it. What would it look like?

**Comment by S0und** [comment]
Sorry, my question wasn't clear enough.

http://i.imgur.com/jEjc2.jpg

**Comment by astropanic** [comment]
I'm glad to hear you like it,

There you go: https://github.com/astropanic/Compline/commit/2a1d0875966ca0e5cc0d859c50bfefb1fe739de0

Multiple selection mode, is that what you wanted ?

**Comment by S0und** [comment]
That's right, thanks!
