### ISSUE TITLE
Hitting the shortcut key with no text on current line

### ISSUE THREAD

**Issue by peppy** [astropanic/Compline#3]
Currently this will bring up the autocomplete dialog box, where you can start typing a line and narrow down completions, but on selecting one it does not appear.

I find this an easier way to use this plugin and would appreciate if you don't need to start typing the line in the document before invoking.

**Comment by astropanic** [comment]
Is that https://github.com/astropanic/Compline/commit/17028c16de56e0683b13e52279ee057bccde1ddc what you mean ?

**Comment by peppy** [comment]
Yep, except now it seems to delete all content of the document after the inserted line!

**Comment by astropanic** [comment]
https://github.com/astropanic/Compline/commit/9524e842fd56ed19b6d5665f8ce42ed69d0a210e fixed

**Comment by peppy** [comment]
I'd love to say it's fixed, except now it is completing with random lines at random, and I have no idea what is going on!

**Comment by astropanic** [comment]
https://github.com/astropanic/Compline/commit/5144d4fe8a4d0fba12e42149f46b664bf4de633a fixed

**Comment by peppy** [comment]
Looking a lot better :+1:. The only thing left I could add is that maybe the completion shouldn't be selected after entry, and the cursor should be placed at the end of the line after completion.

Thanks for this plugin by the way, should come in handy.
